version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
